[package]
name = "dwsh-logout"
version = "0.1.0"
edition = "2024"

[lints.clippy]
pedantic = "warn"

[dependencies]
iced = { version = "0.13.1", features = ["tokio"] }
iced_layershell = "0.13.7"
dwsh-utils = { path = "../utils" }
